[package]
name = "gorpvm"
version = "0.1.0"
authors = ["jordan"]
edition = "2018"
default-run = "run"

[dependencies]

[[bin]]
name = "run"
path = "src/bin/run.rs"

[[bin]]
name = "debug"
path = "src/bin/debug.rs"
