[package]
name = "gorp_tests"
version = "0.1.0"
authors = ["Jordan Grace <jordan@righteye.com>"]
edition = "2018"

[dependencies]
gorp_asm = { path = "../gorp_asm" }
gorp_cpu = { path = "../gorp_cpu" }
